### ISSUE TITLE
将「统一码」改称「万国码」

### ISSUE THREAD

**Issue by ShikiSuen** [MY1L/Unicode#2]
「万国码」这个中文称谓用得更广一些。

**Comment by MY1L** [comment]
我考虑「万国码」这个称谓可能是错的，理由非常多，以下理由不分先后。

1. 字面上地球并没有1万个国，联合国成员相比“1万”差2个数量级；
7. “unicode”这个词看不出“万”或“国”的含义，但明显有“统一”的含义；
2. 统一码编码不按国别，不编码语言（Language）而是字母系统\字母表（Script），比如拉丁、西里尔、CJK，这个是统一码联盟强调的，这与国别无关，未来也不可能；
3. 是可以假设历史上每一朝代、未来所有小国全部加起来过万，但不意味着这些不重合，实际上重合后Language和Script的量都要少几个数量级，统一码恰恰为了**统一**而有意统一重合的编码；
6. 统一码的许多区段对应的Script，现文明已不存在或无国家形式，比如“西夏文”、“契丹小字”；
5. 统一码的许多区段不是Script，比如“麻将”、“表意描述字符”、“光学字符识别”；
3. 统一码的许多区段不是任何国家独有的符号，未来也不可能被某国当作国语，比如“增补箭头甲”“交通及地图符号”；
8. 统一码的许多区段有不可见甚至非字符，比如“控制字”“BOM”“变体选择符补充”、U+FFFF；
9. 统一码有大量符号为某个公司（如苹果、谷歌）甚至个人提供，与某国某标无关。我今天在b站发的视频就介绍了一个个人提供的符号。

以前用「万国码」的人可能会改称「统一码」，但在用「统一码」的人，因为如上理由应该不会改称「万国码」了。因为“几”国码这个名称实在有些限制它字面上的收录范围。

**Comment by MY1L** [comment]
偶然发现“Unicode学术学会”官网有简中页面：
https://www.unicode.org/standard/translations/s-chinese.html 什么是Unicode(统一码)?
> Chinese translation by Jenny K. Pan  黎國珍, Xerox, updated by 洛杉矶翻译

或许官网译者比较倾向于不译🤔

**Comment by 86xiang** [comment]
Unicode联盟官方已经明确了“Unicode”对应的简体中文翻译为“统一码”：https://www.unicode.org/terminology/term_en_zh_Hans_CN.html

**Comment by ShikiSuen** [comment]
@86xiang 這是什麼時候制定的？

**Comment by 86xiang** [comment]
@ShikiSuen 从 Internet Archive 的存档来看，最早在 2019 年 6 月 13 日就有了这个页面：https://web.archive.org/web/20190613202952/https://www.unicode.org/terminology/term_en_zh_Hans_CN.html
更早就不清楚了。

**Comment by MY1L** [comment]
@86xiang 总觉得这些译文不对劲儿，比如“Rich Text：加工文本”“Script：手稿程式”……🤨
