### ISSUE TITLE
建议提供一个不含Monu Last的Noto Unicode版本

### ISSUE THREAD

**Issue by zhenlige** [MY1L/Unicode#4]
现有Noto Unicode中包含Monu Last字形，导致部分字符即使存在支持的备用字体，也无法正常显示

**Comment by MY1L** [comment]
🤔我应该误放了测试用版本。正式版不会有这个。

**Comment by MY1L** [comment]
上个月病了还没好，但这个不能再拖了，赶做了一个5.902版，请看看：https://github.com/MY1L/Unicode/releases/tag/NotoUni6
