### ISSUE TITLE
在Windows10环境下，notounicode7.2字体这些字符还不能显示

### ISSUE THREAD

**Issue by ungtl** [MY1L/Unicode#7]
分别是：
西非书面文字的07FD~07FF这三个字符

格鲁吉亚字母的10C7，10CD，10FD，10FE，10FF，这五个字符

格鲁吉亚字母扩展的全部字符1C90~1CBF

格鲁吉亚字母补充的2D27和2D2D

声调修饰符号的全部字符A700~A71F

缅甸文扩展B的全部字符A9E0~A9FE

缅甸文扩展A的AA7C~AA7F的四个字符

希望下个版本补充这些字符

**Comment by MY1L** [comment]
“如果系统默认字体已经存在能填满某区段的就不加，避免臃肿”
我确实要更新，不过你列出的似乎系统都已经有了？没细看（本问题不错，对于有同样问题的人，我列了份系统字体覆盖清单可以对照：https://github.com/MY1L/Unicode/tree/main/FontList ）
