### ISSUE TITLE
建议更新Noto Unicode

### ISSUE THREAD

**Issue by ungtl** [MY1L/Unicode#9]
最近NotoSansArabic-Regular的阿拉伯部分补全了，建议与Noto Unicode合并

**Comment by MY1L** [comment]
太好啦，其实我前几天看到了，不过正在急着[更新MonuLast](https://twitter.com/MY1Ltype/status/1711365795123691626)、MonuHani到统一码15.1版，这个要延后一点。

**Comment by MY1L** [comment]
啊！NotoSansArabic-Regular v2.011 好像有错啊？我报1个明显的错试试：https://github.com/notofonts/arabic/issues/206

**Comment by sal-ammoniac** [comment]
说起来之前notonaskh还把老维文he的词中显示错了

**Comment by sal-ammoniac** [comment]
另外柯尔克孜文的ۅ有必要做一个下面是环的版本吗？（印刷品里面下面是一杠和环的皆有使用）

**Comment by MY1L** [comment]
@sal-ammoniac 不知道呢，我不懂阿文，不清楚你说的是否是统一码方面的问题，毕竟Noto目标是要遵循统一码来的，正如昨天他们讨论的（https://github.com/google/fonts/pull/6859#issuecomment-1786668337 ）
> Which means we seem to have got ahead of Unicode here. I think since **Noto is an implementation of Unicode**, we may need to back out this change.

像这些我不懂不敢改，如果不反对的话就暂时保留在我的字体里吧：https://github.com/notofonts/arabic/issues/211

**Comment by MY1L** [comment]
好了，同时也更新了一大波其它东西，这是更新清单：
https://github.com/MY1L/Unicode/commit/f6599cfc7d064a1ef66e7333fcbb7c75467fa73b
